spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/chats?useUnicode=true&characterEncoding=utf8mb4&connectionCollation=utf8mb4_unicode_ci
    username: han
    password: han123
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
